### ISSUE TITLE
Gimp snap stopped working after last updates

### ISSUE THREAD

**Issue by corradoventu** [snapcrafters/gimp#10]
```
corrado@corrado-p13-bb-0319:~$ gimp
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Cannot open display: 
corrado@corrado-p13-bb-0319:~$ snap refresh gimp
snap "gimp" has no updates available
corrado@corrado-p13-bb-0319:~$ snap info gimp
name:      gimp
summary:   GNU Image Manipulation Program
publisher: snapcrafters
contact:   https://github.com/snapcrafters/gimp/issues
license:   unknown
description: |
  Whether you are a graphic designer, photographer, illustrator, or scientist,
  GIMP provides you with sophisticated tools to get your job done. You can
  further enhance your productivity with GIMP thanks to many customization
  options and 3rd party plugins.
commands:
  - gimp
snap-id:   KDHYbyuzZukmLhiogKiUksByRhXD2gYV
tracking:  stable
refreshed: 2017-12-11T17:39:25+01:00
installed:   2.8.22 (30) 142MB -
channels:                
  stable:    2.8.22 (30) 142MB -
  candidate: 2.8.22 (25) 141MB -
  beta:      2.8.22 (25) 141MB -
  edge:      2.8.22 (30) 142MB -
corrado@corrado-p13-bb-0319:~$ inxi -SCGx
System:    Host: corrado-p13-bb-0319 Kernel: 4.15.0-12-generic x86_64
           bits: 64 gcc: 7.3.0
           Desktop: Gnome 3.28.0 (Gtk 3.22.28-1ubuntu3)
           Distro: Ubuntu Bionic Beaver (development branch)
CPU:       Dual core Intel Core i3-7100 (-MT-MCP-) 
           arch: Skylake rev.9 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 15648
           clock speeds: max: 3900 MHz 1: 800 MHz 2: 800 MHz 3: 800 MHz
           4: 800 MHz
Graphics:  Card: Intel HD Graphics 630 bus-ID: 00:02.0
           Display Server: x11 (X.Org 1.19.6 ) driver: i915
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2)
           version: 4.5 Mesa 18.0.0-rc4 Direct Render: Yes
corrado@corrado-p13-bb-0319:~$ 

```

**Comment by diddledan** [comment]
Which version of core are you running? Can you post the output of `snap version` please?

**Comment by corradoventu** [comment]
I'm running snapd 2.32+18.04~pre5 and now
i know snapd 2.32+18.04~pre5 is known to be broken, an update is being prepared
[https://forum.snapcraft.io/t/gnome-calculator-problem/4579/2]
here is my snap version and my system. thanks.

> corrado@corrado-p13-bb-0319:~$ snap version
snap    2.32+18.04~pre5
snapd   2.32+18.04~pre5
series  16
ubuntu  18.04
kernel  4.15.0-12-generic
corrado@corrado-p13-bb-0319:~$ inxi -Fx
System:    Host: corrado-p13-bb-0319 Kernel: 4.15.0-12-generic x86_64 bits: 64 gcc: 7.3.0
           Desktop: Gnome 3.28.0 (Gtk 3.22.28-1ubuntu3)
           Distro: Ubuntu Bionic Beaver (development branch)
Machine:   Device: desktop Mobo: ASRock model: H110M-G/M.2 serial: N/A
           UEFI: American Megatrends v: P1.10 date: 05/11/2017
CPU:       Dual core Intel Core i3-7100 (-MT-MCP-) arch: Skylake rev.9 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 15648
           clock speeds: max: 3900 MHz 1: 1020 MHz 2: 3215 MHz 3: 2713 MHz 4: 3176 MHz
Graphics:  Card: Intel HD Graphics 630 bus-ID: 00:02.0
           Display Server: x11 (X.Org 1.19.6 ) driver: i915 Resolution: 1920x1080@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2)
           version: 4.5 Mesa 18.0.0-rc4 Direct Render: Yes
Audio:     Card Intel Sunrise Point-H HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.15.0-12-generic
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e v: 3.2.6-k bus-ID: 00:1f.6
           IF: enp0s31f6 state: up speed: 100 Mbps duplex: full mac: 70:85:c2:44:7b:86
Drives:    HDD Total Size: 1000.2GB (1.4% used)
           ID-1: /dev/sda model: TOSHIBA_DT01ACA1 size: 1000.2GB
Partition: ID-1: / size: 16G used: 5.1G (35%) fs: ext4 dev: /dev/sda13
           ID-2: swap-1 size: 8.59GB used: 0.00GB (0%) fs: swap dev: /dev/sda2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 37.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 243 Uptime: 2 min Memory: 1132.3/7680.8MB
           Init: systemd runlevel: 5 Gcc sys: N/A Client: Shell (bash 4.4.181) inxi: 2.3.56 
corrado@corrado-p13-bb-0319:~$

**Comment by diddledan** [comment]
As you stated, `snapd-2.32+18.04~pre5` is broken. This is your issue. As this is not a problem specifically with this GIMP snap, I'm closing this bug report.
