### ISSUE TITLE
Gimp doesn't start on ubuntu 20.04

### ISSUE THREAD

**Issue by kerusasu** [snapcrafters/gimp#102]
**Gimp version**: 2.10.18
**Operating system**: A fresh install of Ubuntu 20.04 from the daily iso
**Package**: Snap from the stable and edge channels
**Description of the bug**:
Gimp doesn't launch, here's the error message when opening from a terminal:
`/snap/gimp/252/usr/bin/gimp: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory`
**Reproducible**: Always

**Comment by diddledan** [comment]
Can you run this and paste the output, please?

```
snap connections gimp
```

**Comment by kerusasu** [comment]
Sorry it took me a while to respond but it seems to work just fine now and I can't reproduce it. Thanks for the snap!
