### ISSUE TITLE
The number of tools in GIMP Toolbox have reduced. How to restore them?

### ISSUE THREAD

**Issue by sunbearc22** [snapcrafters/gimp#103]
There used to be many tools in the GIMP Toolbox. However, recently after an Update, many of the tools in the Toolbox seems to have been removed. How do I restore the original layout of the Toolbox?
```
$ snap list | grep gimp
gimp                     2.10.18                     252   stable    snapcrafters
```    
I just tried to run gimp from the command line and found the below msg. I also see this msg in other computer.
```
$ gimp
ln: failed to create symbolic link '~/snap/gimp/252/.config/gtk-2.0/gtkfilechooser.ini': File exists
    /snap/gimp/252/usr/bin/gimp: Gimp-Widgets-WARNING: parse_iso_codes: error parsing '/build/gimp/parts/gimp/install/usr/share/xml/iso-codes/iso_639.xml': No such file or directory
```
Systems are using Ubuntu 18.04.

**Comment by diddledan** [comment]
This is an upstream change that the snap simply packages unchanged. See https://www.gimp.org/news/2020/02/24/gimp-2-10-18-released/#tools-now-grouped-by-default for details about this change and how to revert it.
