### ISSUE TITLE
Gimp can't access to /tmp directory 

### ISSUE THREAD

**Issue by nuliknol** [snapcrafters/gimp#120]
I am using GIMP 2.10.20 (default Ubuntu 18 install) version and when I try to pick a file in /tmp directory (in the Open file dialog) Gimp switches to some other /tmp directory where there are no files. 

First I am double-clicking on "File System" icon, then on "tmp" directory, and when I click on "tmp" the directory opens and shows ".snap" entry there. This is not true, I don't have ".snap" directory in "/tmp" directory. 

Could you please fix this bug? It is very annoying to have to move files from /tmp to another places just to open a file in Gimp. I didn't have this problem with prior versions.

Thanks.

**Comment by diddledan** [comment]
Each Snap Package gets its own /tmp folder so that one snap cannot snoop on a different snap. These folders are also separate from your host's /tmp to prevent snooping on system apps and potential sandbox bypass/escape. For these reasons /tmp is not usable to share files with snaps.

**Comment by nuliknol** [comment]
solution:

`snap remove gimp`
and install some other package.
