### ISSUE TITLE
2.10.24:  GIMP-Warning: The batch interpreter 'python-fu-eval' is not available. Batch mode disabled.

### ISSUE THREAD

**Issue by MrMartinuk** [snapcrafters/gimp#150]
Good afternoon,
my Gimp install has been auto updated to 2.10.24 and I've lost my python batch interpreter. I'm running my batch commands as "--batch-interpreter python-fu-eval"

I don't know if this is a gimp 2.10.24 or a snap thing. Any advice?? Can I snap back down to 2.10.22 ???

Running on Centos btw

Thanks.

**Comment by MrMartinuk** [comment]
Ah, I wish I saw your note earlier. I've messed up by doing unitstall/install so now I have no previous revisions :( 
Is there any way to get back to 2.10.22 from this position??

**Comment by diddledan** [comment]
Unfortunately there is no easy way to get a previous revision from the store.

**Comment by MrMartinuk** [comment]
Ah ok :( I’ve had to go the dark side and get up and running via flatpak 

is the current view that this won’t be fixed in snap until Gimp3.0?

**Comment by MrMartinuk** [comment]
That would be greatly appreciated :) Many thanks

**Comment by MrMartinuk** [comment]
Hello, I tried revision 372 which came out today but the issue still persists?? is core18 in 372?

**Comment by diddledan** [comment]
yes, I've dropped back to core18 in revision 372.. The only difference should be that it's updated from GIMP 2.10.22 to 2.10.24

**Comment by MrMartinuk** [comment]
something still not right sadly :( Still reporting the same error, inability to run the python interface.
I've got Gimp-2.10.24 running via flatpack and that runs ok, python interface running ok there.

snap info gimp
installed:          2.10.24            (372) 290MB -

..and simple python script to dump out flatpak GIMP version just to verify: 
> python-eval.py-Warning: VERSION **2.10.24**
