### ISSUE TITLE
AVIF support hasn't been included in the snap version

### ISSUE THREAD

**Issue by paddylandau** [snapcrafters/gimp#166]
Since version 2.10.22, GIMP has [supported AVIF](https://www.gimp.org/news/2020/10/07/gimp-2-10-22-released/). However, the snap version (I'm currently using 2.10.24) is missing this.

I tested the Flatpak version (2.10.28), and it does support AVIF.

I don't know specifically what needs to change to let the snap version of GIMP support AVIF, but I believe that it has something to do with `libheif` and `libde265-0` (I could be wrong!).

Please include support for AVIF.

Thank you

**Comment by ogra1** [comment]
the snap seems to include both these libs ... 
but looking at the snapcraft.yaml file it builds libheif from source first and ships that binary in the snap ... but then the gimp build itself links against the way older libheif-dev package from the archive ... 

i guess someone needs to drop the libheif-dev line from `build-packages:` of the gimp part ...

**Comment by diddledani** [comment]
Thanks, @ogra1. I'd completely missed that `libheif-dev` was still being pulled - I have previously omitted `libheif1` from `stage-packages` but it seems I missed the `-dev` from build-packages 🤦‍♀️

**Comment by jnsgruk** [comment]
This should now be fixed. Closing for now! :)
