### ISSUE TITLE
gimp on Ubuntu 21.10 arch 64 is missing a shared library

### ISSUE THREAD

**Issue by hallorant** [snapcrafters/gimp#176]
```
hallorant@innsmouth:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
hallorant@innsmouth:~$ arch
aarch64
hallorant@innsmouth:~$ gimp
/snap/gimp/382/usr/bin/gimp: error while loading shared libraries: libunwind.so.8: cannot open shared object file: No such file or directory
hallorant@innsmouth:~$ snap list
Name               Version                     Rev    Tracking         Publisher     Notes
bare               1.0                         5      latest/stable    canonical✓    base
chromium           95.0.4638.69                1816   latest/stable    canonical✓    -
core               16-2.52.1                   11996  latest/stable    canonical✓    core
core18             20211028                    2252   latest/stable    canonical✓    base
core20             20211129                    1274   latest/stable    canonical✓    base
gimp               2.10.28                     382    latest/stable    snapcrafters  -
gnome-3-28-1804    3.28.0-19-g98f9e67.98f9e67  160    latest/stable    canonical✓    -
gnome-3-34-1804    0+git.3556cb3               75     latest/stable    canonical✓    -
gnome-3-38-2004    0+git.cd626d1               88     latest/stable/…  canonical✓    -
gtk-common-themes  0.1-59-g7bca6ae             1519   latest/stable/…  canonical✓    -
snap-store         3.38.0-66-gbd5b8f7          559    latest/stable/…  canonical✓    -
hallorant@innsmouth:~$ 

```

I haven't been able to figure out a workaround. installing

```
sudo apt-get install -y libunwind-dev
```

doesn't help

**Comment by Hallerf** [comment]
sudo apt-get install -y libunwind-dev

**Comment by Hallerf** [comment]
> hallorant@innsmouth:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
hallorant@innsmouth:~$ arch
aarch64
hallorant@innsmouth:~$ gimp
/snap/gimp/382/usr/bin/gimp: error while loading shared libraries: libunwind.so.8: cannot open shared object file: No such file or directory
hallorant@innsmouth:~$ snap list
Name               Version                     Rev    Tracking         Publisher     Notes
bare               1.0                         5      latest/stable    canonical✓    base
chromium           95.0.4638.69                1816   latest/stable    canonical✓    -
core               16-2.52.1                   11996  latest/stable    canonical✓    core
core18             20211028                    2252   latest/stable    canonical✓    base
core20             20211129                    1274   latest/stable    canonical✓    base
gimp               2.10.28                     382    latest/stable    snapcrafters  -
gnome-3-28-1804    3.28.0-19-g98f9e67.98f9e67  160    latest/stable    canonical✓    -
gnome-3-34-1804    0+git.3556cb3               75     latest/stable    canonical✓    -
gnome-3-38-2004    0+git.cd626d1               88     latest/stable/…  canonical✓    -
gtk-common-themes  0.1-59-g7bca6ae             1519   latest/stable/…  canonical✓    -
snap-store         3.38.0-66-gbd5b8f7          559    latest/stable/…  canonical✓    -
hallorant@innsmouth:~$

**Comment by hallorant** [comment]
That doesn't appear to solve the problem, see results below:

```
hallorant@innsmouth:~$ sudo apt-get install -y libunwind-dev

[sudo] password for hallorant: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  liblzma-dev
Suggested packages:
  liblzma-doc
The following NEW packages will be installed:
  liblzma-dev libunwind-dev
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 554 kB of archives.
After this operation, 3,584 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports impish/main arm64 liblzma-dev arm64 5.2.5-2 [149 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports impish/main arm64 libunwind-dev arm64 1.3.2-2 [405 kB]
Fetched 554 kB in 1s (617 kB/s)        
Selecting previously unselected package liblzma-dev:arm64.
(Reading database ... 183818 files and directories currently installed.)
Preparing to unpack .../liblzma-dev_5.2.5-2_arm64.deb ...
Unpacking liblzma-dev:arm64 (5.2.5-2) ...
Selecting previously unselected package libunwind-dev:arm64.
Preparing to unpack .../libunwind-dev_1.3.2-2_arm64.deb ...
Unpacking libunwind-dev:arm64 (1.3.2-2) ...
Setting up liblzma-dev:arm64 (5.2.5-2) ...
Setting up libunwind-dev:arm64 (1.3.2-2) ...
Processing triggers for man-db (2.9.4-2) ...
hallorant@innsmouth:~$ snap install gimp
gimp 2.10.28 from Snapcrafters installed
hallorant@innsmouth:~$ gimp
/snap/gimp/384/usr/bin/gimp: error while loading shared libraries: libunwind.so.8: cannot open shared object file: No such file or directory
hallorant@innsmouth:~$ 
```

**Comment by kenvandine** [comment]
It looks like the snap is broken on arm64.  The snap needs to be rebuilt with libunwind bundled I'm the snap.

**Comment by hallorant** [comment]
Super, glad I reported it to the right place. I really wasn't sure if something was broken in Ubuntu adm64 -- it still, at times, seems like a work in progress.

**Comment by waveform80** [comment]
Seems this got fixed at some point? At least, it's now working on kinetic (22.10) for me. I'll re-test on jammy (22.04) if I remember.

**Comment by diddledani** [comment]
@waveform80 you're correct, this got fixed but I didn't close the issue. Thanks for pinging. I'll close it now.
