### ISSUE TITLE
Fonts in ~/.local/share/fonts are not taken into account

### ISSUE THREAD

**Issue by pieqq** [snapcrafters/gimp#21]
Tested on Ubuntu 18.04 with gimp 2.10 (rev 38) installed from stable channel.

### Steps to reproduce
1. Download a font from the Internet, double click on it (it should open with Gnome Fonts)
2. Press Install
3. Open Gimp 2.10 (snap version), create a text layer and try to find the newly installed font

### Actual results
In step 2, the font is installed in `~/.local/share/fonts`. In step 3, this font is not available on Gimp 2.10 (but it is available on Gimp 2.8 installed through `apt`).

If I manually copy the font from `~/.local/share/fonts` to `~/.fonts/` and restart Gimp 2.10, the font is available.

**Comment by diddledan** [comment]
Does removing the gimp snap and reinstalling, after you've added to font to `~/.local/share/fonts` fix it?

**Comment by pieqq** [comment]
Yes. After I reinstall GIMP (`sudo snap install gimp`), the font in `~/.local/share/fonts` is available.

**Comment by diddledan** [comment]
This is a problem with the [desktop-helpers](https://github.com/ubuntu/snapcraft-desktop-helpers) and not specific to gimp. The desktop-helpers only recompile the font cache after a refresh of the snap happens. They do it this way to prevent slow launch times beyond the first after the refresh. Rebuilding the fonts every launch would incur a performance penalty.

**Comment by pieqq** [comment]
Thanks for the feedback.

But...

> If I manually copy the font from `~/.local/share/fonts` to `~/.fonts/` and restart Gimp 2.10, the font is available.

Why does it work with one directory and not the other?

Should I file a bug in the desktop-helpers project?

**Comment by anthony-coble** [comment]
@pieqq did you submit this issue to another repo somewhere? I am experiencing this and would like to follow the resolution.

**Comment by hadware** [comment]
Experiencing this as well

**Comment by Juanlu001** [comment]
I tested `sudo snap remove gimp && sudo snap install gimp` and it worked.

**Comment by freechelmi** [comment]
Juste a note : 

Copying the font to the system-wide dir 

/usr/local/share/fonts 

makes it available in snap Gimp directly.

We should have a way in gnome font viewer to install it system-wide

**Comment by ChemoCosmo** [comment]
Same problem here with GImp 4.10.20 on Ubuntu 18.04.
Only that no solution works: Neither putting the font in `~/.local/share/fonts` or `~/fonts` nor reinstalling Gimp (via snap) afterwards gives acces to the font (Impact) in Gimp. 
Other programs like writer can find and can use the font.

**Comment by mapto** [comment]
Had same situation as @ChemoCosmo (on Ubuntu 20.04 and Gimp 2.10.20). Funny thing is that reinstalling Gimp via snap also solved the same problem on Inkscape.

**Comment by jabowery** [comment]
```
# sudo snap remove gimp && sudo snap install gimp
gimp removed
gimp 2.10.28 from Snapcrafters installed
```
fixed it for me, but I have to wonder why it is I'm getting version 2 while ChemCosmo reports version 4.  Did gimp do a version reset and start numbering over or do I have a fault snap installation?

Also, if some folks are doing a snap reinstall but failing to fix the problem the issue seems to remain open.

Finally, a comment on dependencies:

If desktop-helpers takes it upon itself to defer recompilation of fonts until a snap reinstall, then desktop-helpers needs to be integrated into the version updating system so as to notify the user that they need to update gimp and it should notify the moment a new font is installed.
