### ISSUE TITLE
[Enhancement]: Push GIMP 2.10.34 from latest/edge to latest/stable

### ISSUE THREAD

**Issue by linghengqian** [snapcrafters/gimp#213]
### What changes would you like?

- I noticed that at https://snapcraft.io/gimp, GIMP 2.10.32 is still at latest/edge , it's been a long time, can we push GIMP 2.10.32 to latest/stable?
- ![image](https://user-images.githubusercontent.com/20187731/200517280-54fd3a84-e4ed-4a10-ac0f-9963d0f7ce8a.png)

**Comment by Gersonzao** [comment]
The current version on Snapcraft is still 2.10.30 while there already is 2.10.34 and the development version is 2.99.16, please update it :(

**Comment by linghengqian** [comment]
> The current version on Snapcraft is still 2.10.30 while there already is 2.10.34 and the development version is 2.99.16, please update it :(

- Apparently I don't have this permission.

**Comment by linghengqian** [comment]
- @lucyllewy I wonder if any snapcrafters have time for a new release?

**Comment by Gersonzao** [comment]
> > The current version on Snapcraft is still 2.10.30 while there already is 2.10.34 and the development version is 2.99.16, please update it :(
> 
>     * Apparently I don't have this permission.

Yeah, I know. I really want the snap to be updated because the flatpak uses `--filesystem=host`

**Comment by linghengqian** [comment]
- It looks like the fix is ​​at https://github.com/snapcrafters/gimp/commit/4a4e0431cdbf5435d741ff4f8ab91f7246773835 . The last/stable channel is 2.10.36, while the preview/edge channel is 2.99.10 . 

- The current issue doesn't focus on the preview/edge channel, so even though there is no snapcraft package for 2.99.16, I have to close the current issue.
