### ISSUE TITLE
Printers are not available

### ISSUE THREAD

**Issue by pieqq** [snapcrafters/gimp#22]
Tested on Ubuntu 18.04 with gimp 2.10 (rev 38) installed from stable channel.

### Steps to reproduce

1. Make sure you have some printer configured in your system
2. Open Gimp 2.10 (snap version)
3. Create a document, then try to print it (`Ctrl+P`)

### Actual results
None of the printers are available, only `Print to File` and `Print to LPR`:

![screenshot from 2018-05-14 14-33-21](https://user-images.githubusercontent.com/512471/39981592-c92050ec-5783-11e8-884d-bb1f9424a9dd.png)

If I follow the same steps with Gimp 2.8 (installed through `apt`), I can see all the printers configured on my device and get a document printed.

**Comment by diddledan** [comment]
Can you try:

```bash
$ sudo snap refresh gimp --edge
$ sudo snap connect gimp:cups-control
```

If that works I can push to stable and file a request for `cups-control` to be automatically connected.

**Comment by pieqq** [comment]
It works!

Thanks a lot for the quick fix!

**Comment by diddledan** [comment]
OK, I'll mark this issue closed as fixed.

**Comment by ralgfoen** [comment]
Hi! Got the same issue, except that I'm on Ubuntu 16.04. The workaround mentioned above doesn't help, unfortunately. Is there another way to get printers working?

**Comment by verwilst** [comment]
On ubuntu 18.10, I noticed my printers weren't visible. `snap connect gimp:cups-control` fixed it though. Maybe this connection should be standard? :-)

**Comment by fantauzzi** [comment]
Same issue here with an Epson P50 under Ubuntu 18.04. The workaround provided above worked for me.

**Comment by Conzar** [comment]
Same with Brother on Ubuntu 18.04.  snap connect gimp:cups-control fixed it.

**Comment by DNABRATS** [comment]
Same as all of the other comments on Ubuntu 18.04   
$ sudo snap refresh gimp --edge
$ sudo snap connect gimp:cups-control
Ran both of these commands and it worked like a charm.  Thanks!

**Comment by svenmeier** [comment]
What happened about doing this automatically?
When installing Gimp-snap via software center, there's no easy way for inexperienced users to get their printers working with Gimp.

**Comment by nevyn-hira** [comment]
Took me WAY too long to find this solution. It's a month since the last comment. Is there any chance this is going to be fixed any time soon?

**Comment by dptsolutions** [comment]
This is still happening on my Ubuntu 19.10 installation. Workaround worked, but I was stumped for a while.

**Comment by rsanden** [comment]
This problem doesn't seem to be fixed.
I'm not sure how to re-open this issue like we would do in a normal issue tracking system.

We tried removing and reinstalling gimp via snap, and the problem persisted. Running `snap connect gimp:cups-control` worked.

This github issue shouldn't be resolved until cups connect is performed automatically at installation.

**Comment by cyberb** [comment]
Still does not work, ubuntu 21.04, gimp 2.10.24.
Running `sudo snap connect gimp:cups-control` with gimp restart fixed it.
Why it does not happen automatically?

**Comment by deddc23efb** [comment]
Still does not work in 22.04 - needed to manually run the connect command

**Comment by bendoin** [comment]
Hello. Still does not work in Ubuntu 23.04. Needed to manually run the connect command.

**Comment by berkes** [comment]
And it's 2024, and 24:04, the latest LTS still does not have this fixed.

Seriously, snap might be a good idea, but please polish the rough edges, canonical/snappers. These tiny things sum up to a death by a thousand papercuts.

**Comment by LuchoLopez** [comment]
In my case (I'm using Ubuntu 24.04) the error was caused by snap app. I fexed the issue with this steps:
1. Open Ubuntu's Apps Center
2. Search GIMP and uninstall
3. Open a terminal
4. Run: `sudo apt install gimp`
5. Check the printing dialog on Gimp

Hope this helps.
Luis.-
