### ISSUE TITLE
Point to this issue tracker in the configure script for new releases of GIMP

### ISSUE THREAD

**Issue by pieqq** [snapcrafters/gimp#29]
With GIMP 2.10.2 release, the team introduced [an option for packagers to direct users to the proper bugtracker when facing a bug with a specific build:](https://www.gimp.org/news/2018/05/20/gimp-2-10-2-released/#packagers-set-your-bug-tracker-address)

> This is why our `configure` script now has the `--with-bug-report-url` option, allowing you to set your own bug tracker web URL. This way, when people click the *“Open Bug Tracker”* button it will open the package bug tracker instead.

I guess it would be a good idea to set the `--with-bug-report-url` to this Github repository issue tracker (`https://github.com/snapcrafters/gimp/issues`).

**Comment by diddledan** [comment]
thanks for the notification :-) I'll get right on it!
