### ISSUE TITLE
GIMP UI does not open after launching on Ubuntu 24.04.1.

### ISSUE THREAD

**Issue by TheBugMeister** [snapcrafters/gimp#295]
### What happened?

Description:
************* 
The GIMP user-interface fails to open on the desktop even though
the Gimp icon is on the taskbar with a dot indicating it is active.

Steps To Reproduce:
******************** 
01) Assuming OS is installed
02) Install GIMP using SNAP User Interface
03) Launch GIMP from BASH command line:  gimp &
04) Wait 30 seconds

Expected Results:
*************** 
* The GIMP UI should open on the desktop.

Actual Results:
************* 
* The UI did not open.

Software Version:
*****************
Gimp 2.10.38 - installed with SNAP  (although the same happens if installed with 'apt-get')

Platform Details:
******************
H/W      : LG Gram 17-inch with Intel Core I7 10th Generation w/16GB Memory and 512 GB SSD
OS       : Ubuntu 24.04.1 LTS
Nickname : Noble Numbat
Kernel   : 6.8.0-48-generic Fri Sep 27 2024 @ 14:04:52 UTC

Additional Notes:
****************** 
This problem did not occur when system was running Ubuntu 22.04.
It only started happening after the 'upgrade' to 24.04.

Attachments:
************* 
* Screenshot of expanded icon from taskbar indicating that a Gimp window exists - but the operator cannot find it
![screenshot_of_gimp_context_menu](https://github.com/user-attachments/assets/27e7f95b-bad5-4601-878c-e13ffd0dc1c2)

### What should have happened?

The UI should pop open on the desktop.

### Output of `snap info $snap_name`

```shell
computer:~/snap$ snap info gimp
name:      gimp
summary:   GNU Image Manipulation Program
publisher: Snapcrafters✪
store-url: https://snapcraft.io/gimp
contact:   https://github.com/snapcrafters/gimp/issues
license:   unset
description: |
  Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you
  with sophisticated tools to get your job done. You can further enhance your productivity with GIMP
  thanks to many customization options and 3rd party plugins.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
  
  Upstream Project: https://www.gimp.org/
  snapcraft.yaml Build Definition:
  https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml
commands:
  - gimp
snap-id:      KDHYbyuzZukmLhiogKiUksByRhXD2gYV
tracking:     latest/stable
refresh-date: today at 21:20 CST
channels:
  latest/stable:     2.10.38   2024-05-10 (436) 540MB -
  latest/candidate:  2.10.38   2024-05-10 (436) 540MB -
  latest/beta:       ↑                                
  latest/edge:       ↑                                
  preview/stable:    3.0.0-RC1 2024-11-07 (452) 388MB -
  preview/candidate: 3.0.0-RC1 2024-11-06 (452) 388MB -
  preview/beta:      ↑                                
  preview/edge:      3.0.0-RC1 2024-11-07 (454) 388MB -
installed:           2.10.38              (436) 540MB -
computer:~/snap$
```

### Output of `snap connections $snap_name`

```shell
computer:~/snap$ snap connections gimp
Interface                 Plug                  Slot                              Notes
browser-support           gimp:browser-support  :browser-support                  -
content[gnome-3-38-2004]  gimp:gnome-3-38-2004  gnome-3-38-2004:gnome-3-38-2004   -
content[gtk-2-engines]    gimp:gtk-2-engines    gtk2-common-themes:gtk-2-engines  -
content[gtk-3-themes]     gimp:gtk-3-themes     gtk-common-themes:gtk-3-themes    -
content[icon-themes]      gimp:icon-themes      gtk-common-themes:icon-themes     -
content[sound-themes]     gimp:sound-themes     gtk-common-themes:sound-themes    -
cups-control              gimp:cups-control     -                                 -
dbus                      -                     gimp:dbus-gimp                    -
desktop                   gimp:desktop          :desktop                          -
desktop-legacy            gimp:desktop-legacy   :desktop-legacy                   -
gsettings                 gimp:gsettings        :gsettings                        -
home                      gimp:home             :home                             -
network                   gimp:network          :network                          -
opengl                    gimp:opengl           :opengl                           -
removable-media           gimp:removable-media  -                                 -
unity7                    gimp:unity7           :unity7                           -
wayland                   gimp:wayland          :wayland                          -
x11                       gimp:x11              :x11                              -
computer:~/snap$
```

### Output of `snap version`

```shell
computer:~/snap$ snap version
snap    2.65.3+24.04
snapd   2.65.3+24.04
series  16
ubuntu  24.04
kernel  6.8.0-48-generic
computer:~/snap$
```

### Relevant log output

```shell
[    5.771506] kernel: audit: type=1400 audit(1731468176.804:186): apparmor="DENIED" operation="open" class="file" profile="snap-update-ns.snapd-desktop-integration" name="/proc/1661/maps" pid=1661 comm="5" requested_mask="r" denied_mask="r" fsuid=120 ouid=0
```

### Teminal output of app

```shell
There is no visible output.  That is the problem.
```

**Comment by jnsgruk** [comment]
Hey! Can you try the snap on the preview track with `sudo snap refresh gimp --channel preview/stable`

**Comment by TheBugMeister** [comment]
Good evening Jon,

Thanks.   That seems to have corrected the issue.  My Gimp now appears to be fully operational.
I would say this resolves the issue.   Do I close the defect, or do you have to close it?

... and Thanks Again!   I love Gimp, and not having it was a real inconvenience  (as computers go).

--Bug
________________________________

**Comment by TheBugMeister** [comment]
Closing ticket as 'Resolved'.

**Comment by jnsgruk** [comment]
That's great, the preview branch is right up to date with the latest release candidate version of GIMP 3, so there may be *some* bugs - but the foundations of the snap itself are much simpler and more modern so I suspect it'll work better overall.

Keep an eye out on this repo for when GIMP 3 releases, as it'll then be back on `latest/stable`!
