### ISSUE TITLE
[2.10.2] snap remove gimp removes all local user configuration

### ISSUE THREAD

**Issue by marcelpaulo** [snapcrafters/gimp#33]
`snap remove gimp` removes all files from *~/snap/gimp*, so all local user config is lost. Shouldn't local user config be left behind when a package is uninstalled ? That's standard practice for all package managers.

**Comment by popey** [comment]
Thanks for the issue report, sorry for the delay getting back to you. This isn't a gimp snap specific issue, but a snap design decision. I personally agree with you, and believe the snapd team are looking alternatives such as `remove` vs `purge`. I'd encourage you to bring this up on the [snapcraft forum](https://forum.snapcraft.io/)

**Comment by marcelpaulo** [comment]
Thanks for explaining it, @popey. gimp was the first and only snap I removed (because of #32), so I thought it was a specific behavior.
