### ISSUE TITLE
Printers not available on Ubuntu 16.04

### ISSUE THREAD

**Issue by ralgfoen** [snapcrafters/gimp#37]
Same as issue [#22](https://github.com/snapcrafters/gimp/issues/22) (closed) The only difference is, that I’m on Ubuntu 16.04. The workaround

`$ sudo snap refresh gimp --edge`
`$ sudo snap connect gimp:cups-control`

doesn’t help, unfortunately.

 Is there another way to get printers working?

**Comment by diddledan** [comment]
please switch back to stable now, and try again. You might need to double-check that the interface is definitely connected by running `snap interfaces gimp`.

**Comment by diddledan** [comment]
I'm going to close this for now. Please re-open if it's still an issue.
