### ISSUE TITLE
GIMP 2.10 does not review the contents of /media/*

### ISSUE THREAD

**Issue by ggshaman888** [snapcrafters/gimp#40]
1. GIMP 2.10 does not review the contents of /media/*
2. It could be in a folder on an external drive.
3 but stumbled on an error. Error opening directory '/media/alexandr/16663f38-1066-4705-8799-0ab393b5acfc/home/alexandr1': Permission denied

ProblemType: Bug
DistroRelease: Ubuntu 16.04
Package: evince 3.18.2-1ubuntu4.3
ProcVersionSignature: Ubuntu 4.15.0-32.35~16.04.1-generic 4.15.18
Uname: Linux 4.15.0-32-generic x86_64
NonfreeKernelModules: wl
ApportVersion: 2.20.1-0ubuntu2.18
Architecture: amd64
CurrentDesktop: Unity
Date: Fri Aug 17 16:01:26 2018
InstallationDate: Installed on 2018-08-17 (0 days ago)
InstallationMedia: Ubuntu 16.04.4 LTS "Xenial Xerus" - Release amd64 (20180228)
SourcePackage: evince
UpgradeStatus: No upgrade log present (probably fresh install

**Comment by diddledan** [comment]
You need to give GIMP the required permission to access `/media`.

On Ubuntu you can do this in "Software" by choosing to allow the permission labelled "Read/write files on removable devices":

![image](https://user-images.githubusercontent.com/147548/44270448-7c74eb80-a22f-11e8-82f5-485ee74ed89f.png)

On all other systems this can be done on the command-line by running the following in a terminal:

```bash
sudo snap connect gimp:removable-media
```
