### ISSUE TITLE
2.10 too slow with xubuntu 16.04

### ISSUE THREAD

**Issue by XzuRukneg** [snapcrafters/gimp#43]
Hello.
Searching a solution for the cage tool issue (https://bugs.launchpad.net/ubuntu/+source/gimp/+bug/1614593), I've tried this snap package. It runs and solve the cage tool issue.
As alexis-scheuer mentioned it, it is very slow for certain operation. For example, make a square selection take 3 or more seconds! When I use it, I can make a square in "real time", but when I do my selection (release mouse button) it takes lots of time to be effective (the soft freeze during this time). Same for select layer.
Note that other tools like 3d transform run fine and quick, in "real time". Computing operation not seem affected.

**Comment by diddledan** [comment]
Is this still an issue with more-recent builds? Could you test again and report back, please? :-)

**Comment by XzuRukneg** [comment]
Sorry, I use flat pack instead.
