### ISSUE TITLE
Adding G'MIC

### ISSUE THREAD

**Issue by KristijanZic** [snapcrafters/gimp#50]
I've downloaded the G'MIC for Gimp 2.10, extracted the shared library, put it in the "~/snap/gimp/47/.config/GIMP/2.10/plug-ins" directory and have made it executable. It doesn't work when I use it with the Gimp snap. 
What am I missing here?

**Comment by allkhor** [comment]
Maybe related: 
`/home/user/snap/gimp/47/.config/GIMP/2.10/plug-ins/gmic/gmic_gimp_qt: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory`

**Comment by KristijanZic** [comment]
The lead of G'MIC says he doesn't know how to fix this, it seems to me to be a snap issue.
https://github.com/dtschump/gmic/issues/80

**Comment by LyzardKing** [comment]
As far as I can tell the dependencies or g'mic should be in the gimp snap.
One thing to do would be to add them directly,
or to create a track with g'mic, so that users can choose which to install.
@diddledan which would be better?

**Comment by Lin-Buo-Ren** [comment]
> it seems to me to be a snap issue messing with the libs?

No, it is because the plugin requires dependency that can't be satisfied by the snap (as GIMP is a Gtk application, there's no chance that the snap will pack Qt libraries)

This issue is not solvable unless the snap uses classic confinement and allows loading out-of-snap libraries when loading the plugin, I doubt that will ever be done in the near future.

**Comment by KristijanZic** [comment]
Any news on this @diddledan ?

**Comment by peerwal** [comment]
Gimp, not being a monolithic applcation, is to a great extent living on adding plug-ins. So, I am not sure, whether it makes terribly much sense to publish a Gimp snap release which drastically reduces the capability of adding plug-ins. Especially, often used plug-in such as G'mic (even if qt-based) will be missed by many users.
