### ISSUE TITLE
Installed Gimp 2.10.6 from Ubuntu Software Center not launching

### ISSUE THREAD

**Issue by 3DLVarq** [snapcrafters/gimp#52]
![screenshot from 2018-10-26 09-03-57](https://user-images.githubusercontent.com/44570580/47643566-9a719d00-db4a-11e8-9ce9-7d1b85d427b5.png)

Gimp seems to be installed though is not launching.

**Comment by popey** [comment]
Thanks for the issue report @3DLVarq. Can you please paste the output of the following commands:-

`snap list`

`snap version`

**Comment by 3DLVarq** [comment]
You are welcome @popey , thanks for your attention.

Yes I can but the issue happened after a clean Ubuntu 16.04.5 reinstall (that is when I took the screenshot).  After a 2nd os reinstall I tried again and the issue seemed to be repeating. Then I have installed Snapcraft and that seemed to act as a workaround (?), now Gimp runs ok.

Output for snap list, version is:

![screenshot from 2018-10-30 09-45-03](https://user-images.githubusercontent.com/44570580/47718961-84d2a500-dc28-11e8-9749-0844994b4058.png)

**Comment by diddledan** [comment]
@popey I bet this is due to gimp being the first snap installed on the system, because it has a base of `core18` so the `core` snap wasn't pulled automatically even though it's needed by the system to provide `snapd`.

**Comment by diddledan** [comment]
@3DLVarq is this still an issue for you?

**Comment by 3DLVarq** [comment]
Thanks for your support, I didn't do a new system reinstall after the issue, gimp is actually running
________________________________
