### ISSUE TITLE
broken gimp snap

### ISSUE THREAD

**Issue by Lvaskz** [snapcrafters/gimp#63]
Hi, I'm using linuxmint 19.1. I installed gimp snap, the package is broken,  the interface has missing icons and mypaint brushes not exist.

**Comment by diddledan** [comment]
mypaint brushes will be fixed in PR #64 

Regarding the missing icons, can you do a screenshot for me please? It might help me for you to highlight in the image where icons are missing. Many thanks :-)

**Comment by Lvaskz** [comment]
Hi, I installed package again via snapstore, It seems work well

**Comment by garikaib** [comment]
Happened to me with the latest snap as well this time on Deepin 15.10. I simply restarted GIMP again and the issue seemed fixed. I didn't even restart my laptop. I am not familiar with how it all works but maybe something needs to refreshed or something. Also I had just removed the official flatpak version of GIMP as it was giving me issues. It could be that as well.
