### ISSUE TITLE
gimp does not recognize the system language, only English language

### ISSUE THREAD

**Issue by Lvaskz** [snapcrafters/gimp#7]
Hi, I can not configure gimp to the Spanish language, this gimp snap is configured only for English. When can we configure the system language, which in this particular case; it is Spanish?
linuxmint 18.2

**Comment by Lvaskz** [comment]
hi, some advance?

**Comment by MichaelKofler** [comment]
still unsolved?

**Comment by diddledan** [comment]
Thanks for keeping tabs on this. I'm not sure whether this is a problem with my build, or with snaps in general. I'll try to investigate some more...

**Comment by diddledan** [comment]
I think I've fixed it. Can you try:

```bash
$ sudo snap refresh --candidate gimp
```
Then run GIMP and see if the localisation/translation is working?

**Comment by MichaelKofler** [comment]
works for me (German localization), thank you!

**Comment by Lvaskz** [comment]
hi, works for me too, thank you

**Comment by diddledan** [comment]
closing as fixed :-) thanks for testing
