### ISSUE TITLE
Cage transform tool crashes always

### ISSUE THREAD

**Issue by felipecock** [snapcrafters/gimp#8]
Hello, there is a bug with the Cage Transform tool. When I close the loop, Gimp gets stuck and I have to kill the process.
I'm using GIMP 2.8.16 on Xubuntu 16.04.
![captura de pantalla_2017-11-07_13-46-48](https://user-images.githubusercontent.com/26395118/32514699-6f132dd0-c3c3-11e7-92bb-1476b400619c.png)

**Comment by diddledan** [comment]
Did you install GIMP via snap or the Ubuntu Repositories? The current snapped version, which this repo is for, is 2.8.22 (build 25).

**Comment by felipecock** [comment]
I had GIMP installed via Ubuntu repository, but then I added the [otto06217](https://launchpad.net/~otto-kesselgulasch/+archive/ubuntu/gimp) ppa repository and then I upgrade my GIMP and their libraries to the latest stable version, but it doesn't fix the issue (same bug).
Finally, I read a blog where suggest install the beta version (unstable) via adding new ppa ([otto-kesselgulasch/gimp-edge](https://launchpad.net/~otto-kesselgulasch/+archive/ubuntu/gimp-edge)) and it was finally solved, I hope the bug doesn't appear anymore on future stable versions.

**Comment by diddledan** [comment]
This issue tracker is for GIMP in snap packages. To file a bug for GIMP from the Ubuntu Repository run `ubuntu-bug gimp` or go to https://bugs.launchpad.net/ubuntu/+source/gimp/+filebug
