### ISSUE TITLE
Gimp 2.10.14 is released, please update the snap

### ISSUE THREAD

**Issue by KristijanZic** [snapcrafters/gimp#80]
As the title says, the new version of Gimp has been released and it would be good to update the snap to the latest version.

**Comment by diddledan** [comment]
not according to gimp.org. There it still shows the latest release as 2.10.12.

**Comment by diddledan** [comment]
Looks like there's a bug in compilation. I can work around this, or wait until the MR reaches the tarball/release

https://gitlab.gnome.org/GNOME/gimp/merge_requests/175

**Comment by KristijanZic** [comment]
Hey, thanks for taking the time!
Maybe go around it for this release?
It'll probably be months before the new one is out.

**Comment by dennismayr** [comment]
One more thing:

This snap used to work on Ubuntu 14.04 i386; it was the only way to have GIMP 2.10 on 32-bit architecture.

Since yesterday, it can't be installed :(

(Snaps are the only way to keep these older machines working with up-to-date software)

**Comment by psymole** [comment]
Hi Daniel, any news on getting 2.10.14 as a snap. Anything I can do to help?

**Comment by JerareYoshi** [comment]
Any news for GIMP 2.10.14 snap package ?

**Comment by diddledan** [comment]
Closing the issue. 2.10.18 is stable and 2.10.20 is candidate
