### ISSUE TITLE
Pre load resources for quick start

### ISSUE THREAD

**Issue by jondoig** [snapcrafters/gimp#9]
Hey just dropping in to say I love GIMP but it takes ages to start on Windows.

At the **very top of my feature wishlist** would be a quick-start by pre-loading resources in the background. This could happen by default but also be subject to settings that could be modified in Edit > Preferences.

The pre-load could even be scheduled at a time after start-up, so as not to unnecessarily slow system startup.

**Comment by diddledan** [comment]
Hi,

You've found the snapcrafters repository for the "snap" package of GIMP which runs on many Linux systems. Unfortunately snap packages do not work on Windows, so we can't support you with your request to preload GIMP data at start-up. The official GIMP support venues more able to help you are at [bug tracker](https://www.gimp.org/bugs/), [developers' mailing list](https://www.gimp.org/mail_lists.html), and [IRC Chat server irc.gimp.org channel #gimp](irc://irc.gimp.org/#gimp).

**Comment by jondoig** [comment]
Yes sorry about that I realised after posting.

**Comment by diddledan** [comment]
No problem :-). I hope you get your problem resolved, even though we don't have the expertise here. The links in my previous post should help somewhat (I think).
