### ISSUE TITLE
Cannot open files in hidden folders

### ISSUE THREAD

**Issue by christian-rauch** [snapcrafters/gimp#98]
I am unable to open an image in a hidden folder, e.g. `gimp $HOME/.gazebo/pictures/*.jpg`.

I have all available permissions enabled:
![gimp_snap_permissions](https://user-images.githubusercontent.com/8226248/74427524-29451e80-4e4f-11ea-848b-629cee7b767a.png)
and I can open a file if I move it from the hidden folder to somewhere not hidden inside my home folder.

**Comment by popey** [comment]
This is expected behaviour when snapped I'm afraid. The `home` interface doesn't permit access to hidden folders in `$HOME` to prevent applications doing nafarious things like stealing your ssh or GPG keys. Sorry for the inconvenience.

**Comment by christian-rauch** [comment]
Good to know. I always thought the `home` interface means access to all of `$HOME`.
The justification is reasonable for untrustworthy processes but brings some inconveniences for others. Isn't there something like a "portal" that allows snaps tp access these files with a user acknowledgement via a GUI interface?
