### ISSUE TITLE
Gimp cannot access all drives

### ISSUE THREAD

**Issue by LoveIsGrief** [snapcrafters/gimp#99]
From what I understand it needs the block-devices plug in order to do so. Could you add it please? It's not possible to access my external hard-drives or even `/tmp`.

```
$ snap list | grep gimp
gimp                     2.10.12                     227   stable    snapcrafters  -
```

P.S thank you for the snap! Ubuntu is woefully behind on gimp releases.

**Comment by diddledan** [comment]
`block-devices` is a permission to allow raw access to storage devices not the files on them, this is not what you want. This snap already has the required `removable-media` plug defined which will allow you to access the paths `/media/$USER/*`, `/mnt`, and `/run/user/$UID/gvfs/*`. You simply need to accept the extra permission by either running `snap connect gimp:removable-media` or using the Software Centre (on ubuntu) to access the permissions pane and toggle the switch.

**Comment by LoveIsGrief** [comment]
Thanks @diddledan . It now works for my external drives. What about `/tmp` ?

**Comment by diddledan** [comment]
Unfortunately each strictly-confined snap you install will get its own `/tmp`, so there are no interfaces that cover providing access to the host's `/tmp`.

**Comment by LoveIsGrief** [comment]
That's a pity :/  I guess I can close this then.

Thanks for your time
